// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalkRevise.Database;

#nullable disable

namespace NZWalkRevise.Migrations
{
    [DbContext(typeof(NZWalkDbContext))]
    [Migration("20250324121010_SeedingDataToDB")]
    partial class SeedingDataToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalkRevise.Models.DomainModels.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aba0e9fa-6146-40b4-b813-20a5f9a4872d"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("d62a659f-0b5b-4e2a-ab4b-bd636c185a46"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("488d8c58-aa04-4023-b10d-db3d85b54b97"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalkRevise.Models.DomainModels.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ce23c73-b1f3-48a4-9102-9dc079f29d4e"),
                            Code = "NLD",
                            Description = "Northland is a region in the northernmost part of New Zealand. Northland is the warmest region in New Zealand.",
                            Name = "Northland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Northland_region_locator_map.svg/1200px-Northland_region_locator_map.svg.png"
                        },
                        new
                        {
                            Id = new Guid("c4a251c6-4eff-4c51-977c-719542149fa7"),
                            Code = "AKL",
                            Description = "Auckland is a metropolitan city in the North Island of New Zealand. The most populous urban area in the country.",
                            Name = "Auckland",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Northland_region_locator_map.svg/1200px-Northland_region_locator_map.svg.png"
                        },
                        new
                        {
                            Id = new Guid("18608543-2350-4e91-b553-41c62c376dd8"),
                            Code = "WKT",
                            Description = "Waikato is a region in the upper North Island of New Zealand. Waikato is known for its dairy farming and horse breeding.",
                            Name = "Waikato",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Northland_region_locator_map.svg/1200px-Northland_region_locator_map.svg.png"
                        },
                        new
                        {
                            Id = new Guid("00f69924-2bac-4589-a7ea-956a091259fb"),
                            Code = "BOP",
                            Description = "The Bay of Plenty is a region in the North Island of New Zealand. The region takes its name from the large bay at its heart.",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Northland_region_locator_map.svg/1200px-Northland_region_locator_map.svg.png"
                        });
                });

            modelBuilder.Entity("NZWalkRevise.Models.DomainModels.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalkRevise.Models.DomainModels.Walk", b =>
                {
                    b.HasOne("NZWalkRevise.Models.DomainModels.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalkRevise.Models.DomainModels.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
